export const ADD_TODO_ACTION = 'ADD_TODO_ACTION'
export const GET_TODO_ACTION = 'GET_TODO_ACTION'
export const UPDATE_TODO_ACTION = 'UPDATE_TODO_ACTION'
export const DELETE_TODO_ACTION = 'DELETE_TODO_ACTION'
export const COMPLETE_TODO_ACTION = 'COMPLETE_TODO_ACTION'
export const LOGIN = 'LOGIN';